apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- base/shuailli-cert.yaml
- base/mall-gateway.yaml
- base/mall-gateway-ingress.yaml
- base/mall-product.yaml

namespace: mall
images:
- name: mall-gateway-image-placeholder
  newName: lishuaidev/mall-gateway
  newTag: 01791cce97e905bb62f049a189094a9afd818437-dev
- name: mall-product-image-placeholder
  newName: lishuaidev/mall-product
  newTag: cb5d050e0bb18f3ddadc5ca63206eaeabd313548-dev
